apiVersion: v1
kind: Service
metadata:
  name: database
  namespace: default 
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 9009
  selector:
    pod-name: database
  type: ClusterIP

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: database
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      pod-name: database
  template:
    metadata:
      labels:
        pod-name: database
    spec:
      containers:
      - name: database
        image: "docker.io/icecrawler/database:latest"
        imagePullPolicy: Always 
        ports:
        - name: http
          protocol: TCP
          containerPort: 9009


