apiVersion: v1
kind: Service
metadata:
  name: kong
  namespace: default
spec:
  ports:
  - name: proxy
    port: 80
    protocol: TCP
    targetPort: 8000
    nodePort: 30000
  - name: admin
    port: 8001
    protocol: TCP
    targetPort: 8001
    nodePort: 30001
  selector:
    pod-name: kong
  type: LoadBalancer

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: kong
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      pod-name: kong
  template:
    metadata:
      labels:
        pod-name: kong
    spec:
      containers:
      - name: kong
        image: "docker.io/pamiel/kong-oidc"
        imagePullPolicy: IfNotPresent
        ports:
        - name: proxy
          protocol: TCP
          containerPort: 8000
        - name: admin
          protocol: TCP
          containerPort: 8001
        env:
        - name: KONG_DATABASE
          value: "off"
        - name: KONG_PROXY_LISTEN
          value: "0.0.0.0:8000"
        - name: KONG_ADMIN_LISTEN
          value: 0.0.0.0:8001