apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-config
  labels:
    app: postgres
data:
  POSTGRES_DB: icecrawler_users_db
  POSTGRES_USER: username
  POSTGRES_PASSWORD: password
